# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('head', models.CharField(blank=True, max_length=50)),
                ('text', models.TextField(blank=True, max_length=100)),
                ('img_lg', models.ImageField(blank=True, upload_to='')),
                ('img_md', models.ImageField(blank=True, upload_to='')),
                ('img_sm', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
