# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mac',
            name='img_lg',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='mac',
            name='img_md',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='mac',
            name='img_sm',
            field=models.ImageField(upload_to=''),
        ),
    ]
