# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170526_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mac',
            name='img_md',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
