# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170526_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mac',
            name='head',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mac',
            name='img_sm',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mac',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mac',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
