# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170526_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mac',
            name='text',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
