# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170526_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ipad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('head', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True, max_length=100, verbose_name='Текст')),
                ('img_lg', models.ImageField(upload_to='')),
                ('img_md', models.ImageField(blank=True, upload_to='')),
                ('img_sm', models.ImageField(blank=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('head', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True, max_length=100, verbose_name='Текст')),
                ('img_lg', models.ImageField(upload_to='')),
                ('img_md', models.ImageField(blank=True, upload_to='')),
                ('img_sm', models.ImageField(blank=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Iwatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('head', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True, max_length=100, verbose_name='Текст')),
                ('img_lg', models.ImageField(upload_to='')),
                ('img_md', models.ImageField(blank=True, upload_to='')),
                ('img_sm', models.ImageField(blank=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='mac',
            name='text',
            field=models.TextField(blank=True, max_length=100, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='mac',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Category'),
            preserve_default=False,
        ),
    ]
