# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20170531_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='zindex',
            field=models.BooleanField(default=0),
        ),
    ]
